### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by rufuspollock** [ropenscilabs/datapkg#2]
Various people have asked for install instructions

**Comment by gsilvapt** [comment]
Even though I am not sure what packages is this dependent of, to install packages from source in R, clone the repo and then run the following code (in Linux systems at least):

`install.packages(path_to_file, repos = NULL, type="source")`

Worst case scenario you have to see the errors log and install those one by one.

**Comment by jeroen** [comment]
Updated the readme with install instructions.
